name: hourse_lux
description: A new Flutter project.
publish_to: "None"

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.6
  get: 4.6.6
  another_flushbar: ^1.12.30
  flutter_screenutil: 5.9.0
  calendar_date_picker2: 0.5.3
  google_fonts: 6.0.0
  http: ^1.1.0
  get_storage: any
  panara_dialogs: ^0.1.4
  nb_utils: 6.0.4
  pinput: 3.0.1
  firebase_core: 2.16.0
  firebase_storage: 11.2.7
  image_picker: 1.0.4
  shimmer: any
  url_launcher: 6.1.14
  cached_network_image: any
  flutter_animated_loadingkit: ^0.0.7
  intl:
  shortuid: ^1.0.0
  table_calendar: any
  sn_progress_dialog: ^1.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/app_icon.png
    - assets/images/women.png
    - assets/record_type/
    - assets/reports/

  fonts:
    - family: Quicksand-Bold
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
    - family: Quicksand-Light
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
    - family: Quicksand-Medium
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
    - family: Quicksand-Regular
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: Quicksand-SemiBold
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
