// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAccqqSrkBYn5Qy-0QSevp0IzGte2u-JOg',
    appId: '1:671280788159:web:2f50716c1a52a94bdc8c0a',
    messagingSenderId: '671280788159',
    projectId: 'horselux-167fb',
    authDomain: 'horselux-167fb.firebaseapp.com',
    storageBucket: 'horselux-167fb.appspot.com',
    measurementId: 'G-PZ1B67EE2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_KZuOq8aKjNQfSTCioB9raFDHK6yW_WA',
    appId: '1:671280788159:android:8b7ad0f960915bf7dc8c0a',
    messagingSenderId: '671280788159',
    projectId: 'horselux-167fb',
    storageBucket: 'horselux-167fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChybQsz0X_y-VqmkuWwgN_e5OhQl382og',
    appId: '1:671280788159:ios:fc2148a041edde33dc8c0a',
    messagingSenderId: '671280788159',
    projectId: 'horselux-167fb',
    storageBucket: 'horselux-167fb.appspot.com',
    iosClientId: '671280788159-kh1k652plmbq1cvkqq6iif7mim21i9gj.apps.googleusercontent.com',
    iosBundleId: 'com.horselux.horselux',
  );
}
